arch init
modified installer script to support arch linux

diff --git a/bash/installer/levant b/bash/installer/levant
--- a/bash/installer/levant
+++ b/bash/installer/levant
@@ -6,18 +6,30 @@ set -o nounset
 set -o pipefail
 export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 if [ ! $(which sudo) ]; then
-	echo 'Please install "sudo" package'
+	echo 'Please install "sudo" package' 1>&2
 	exit 1
 fi
-if [ -n "$(command -v apt-get)" ]; then
-  echo "*** Detected Debian based Linux"
-  export DEBIAN_FRONTEND=noninteractive
-  sudo apt update -qq > /dev/null 2>&1
-  sudo apt install -yqq git > /dev/null 2>&1
+if [[ $EUID -e 0 ]]; then
+   echo "You must run this script as non-root user with sudo permission." 1>&2
+   exit 1
 fi
 if [ -n "$(command -v go)" ]; then
-  echo "*** go toolchain detected. building levant from source"
+  echo "*** go toolchain detected. building levant from source." 1>&2
   export GO111MODULE=on
+  if [ -n "$(command -v apt-get)" ]; then
+    echo "*** Detected Debian based Linux" 1>&2
+    export DEBIAN_FRONTEND=noninteractive
+    sudo apt update -qq > /dev/null 2>&1
+    sudo apt install -yqq git > /dev/null 2>&1
+  fi
+  if [ -n "$(command -v pacman)" ]; then
+    echo "*** Detected Arch based Linux" 1>&2
+    sudo pacman --noconfirm --needed -Sy git
+  fi
+  if [ ! $(which git) ]; then
+    echo 'Please install "git" package' 1>&2
+    exit 1
+  fi
   sudo rm -rf "$(go env GOPATH)/src/github.com/hashicorp/levant"
   sudo rm -rf "$(go env GOPATH)/bin/levant"
   mkdir -p  "$(go env GOPATH)/src/github.com/hashicorp"
@@ -27,10 +39,26 @@ if [ -n "$(command -v go)" ]; then
   popd > /dev/null 2>&1
   sudo mv "$(go env GOPATH)/bin/levant" /usr/local/bin/levant
 else 
-  echo "*** go toolchain not found. downloading latest release from git"
+  echo "*** go toolchain not found. downloading latest release from git" 1>&2
   if [ -n "$(command -v apt-get)" ]; then
     sudo apt update -qq > /dev/null 2>&1
     sudo apt install -yqq curl jq wget > /dev/null 2>&1
+  fi
+  if [ -n "$(command -v pacman)" ]; then
+    echo "*** Detected Arch based Linux" 1>&2
+    sudo pacman --noconfirm --needed -Sy curl jq wget
+  fi
+  if [ ! $(which curl) ]; then
+    echo 'Please install "curl" package' 1>&2
+    exit 1
+  fi
+  if [ ! $(which wget) ]; then
+      echo 'Please install "wget" package' 1>&2
+      exit 1
+  fi
+  if [ ! $(which jq) ]; then
+    echo 'Please install "jq" package' 1>&2
+    exit 1
   fi
   curl -sL https://api.github.com/repos/hashicorp/levant/releases/latest | jq -r '.assets[]|select(.browser_download_url | (contains("linux") and contains("amd64") and (contains("sha256") | not))).browser_download_url' | xargs -I {} \
     sudo wget --quiet --no-cache -O /usr/local/bin/levant {}
