Update key-get

diff --git a/bash/util/key-get b/bash/util/key-get
--- a/bash/util/key-get
+++ b/bash/util/key-get
@@ -8,24 +8,22 @@ if [ ! $(which sudo) ]; then
 	echo 'Please install "sudo" package' 1>&2
 	exit 1
 fi
-echo "after adding sources, there may be missing keys.the following " > /dev/null
-echo "snippet imports all missing keys from keyserver.ubuntu.com    " > /dev/null
-key_server="keyserver.ubuntu.com"; \
-missing_keys=$(apt update 2>&1 1>/dev/null|grep 'NO_PUBKEY'|grep -oE '[^ ]+$'); \
-missing_keys=$(echo "$missing_keys" | xargs -n1 | sort -u | xargs ); \
-key_count=$(echo "$missing_keys"|wc -w); \
-if [[ "$key_count" -gt 0 ]]; then \
-  for i in "$missing_keys"; do \
-  echo "Adding missing GPG key: $i"; \
-  apt-key adv --keyserver  "$key_server" --recv-keys "$i" >/dev/null 2>&1 ; \
-  if [[ "$?" -eq 0 ]]; then \
-  gpg -a --export "$i" | apt-key add - ; \
-  apt update ; \
-  else \
-  echo "Could not find GPG key $i"; \
-  fi \
-  done ; \
-else \
-  echo "No missing keys detected. Yaaaay" ; \
+echo >&2 "*** key-get: trying to import all missing keys from keyserver.ubuntu.com"
+key_server="keyserver.ubuntu.com"
+missing_keys=$(sudo apt-get update 2>&1 1>/dev/null|grep 'NO_PUBKEY'|grep -oE '[^ ]+$')
+missing_keys=$(echo "$missing_keys" | xargs -n1 | sort -u | xargs )
+export key_count=$(echo "$missing_keys"|wc -w)
+if [[ "$key_count" -gt 0 ]]; then
+  for i in "$missing_keys"; do
+  echo >&2 "*** Adding missing GPG key: $i"
+  sudo apt-key adv --keyserver  "$key_server" --recv-keys "$i" >/dev/null 2>&1
+  if [[ "$?" -eq 0 ]]; then
+    gpg -a --export "$i" | sudo apt-key add -
+    sudo apt-get update
+  else
+    echo >&2 "*** Could not find GPG key $i"
+  fi
+  done
+else
+  echo >&2 "*** No missing keys detected. Banzai!"
 fi
-
